### ISSUE TITLE
hlt instruction qemu-kvm

### ISSUE THREAD

**Issue by threeearcat** [dpw/kvm-hello-world#2]
Hi.

I'm trying to implement that a user program in a guest OS executes an instruction(or function) and qemu receives it.
What you mentioned about vmcall and hlt is really helpful and your hello world example can do what I wanna do exactly.

I can find the `ioctl(KVM_RUN)` in `kvm-all.c` in the qemu source tree. I added a test code right after this ioctl and checked that exit_reason is same with `KVM_EXIT_HLT`.
First, I executed hlt instruction in a user program in a guest machine.
It caused a segfault and qemu received nothing. I thought it is because hlt is a privileged instruction.

So I added a syscall which just executes hlt into a guest kernel, and make a user program execute this syscall.
But qemu's exit reason was never the same as a `KVM_EXIT_HLT`.

Using perf tool, however, I can see that there are a lot of vm exit caused by the halt when I executed this syscall repeatedly. It seems that vmexit is occured, but because of somewhat reason, it is not delivered to qemu.

It might be trivial problem... but I'm really new to low level things.
What did I miss?

I will be really appreciated if you give me an advice.
Thanks in advance.

**Comment by dpw** [comment]
Hi,

I guess that under qemu-kvm, you are hitting the `lapic_in_kernel` case at https://github.com/torvalds/linux/blob/master/arch/x86/kvm/x86.c#L6160

A lapic gets added to each vcpu created at https://github.com/torvalds/linux/blob/master/arch/x86/kvm/x86.c#L6160.  That happens if KVM_CREATE_IRQCHIP was called.  It seems likely that's what qemu-kvm does.

Unfortunately, kvm does not offer a generic way for guests to signal to the non-kernel part of the hypervisor.  I'm not sure what the easiest way is if HLT doesn't work for you.  Maybe an OUT instruction to some IO port number that is not handled by kvm?
